// Generated by the lithium symbol generator.
#include <lithium_symbol.hh>
#ifndef LI_SYMBOL_date_of_birth
#define LI_SYMBOL_date_of_birth
    LI_SYMBOL(date_of_birth)
#endif

#ifndef LI_SYMBOL_fight_skills
#define LI_SYMBOL_fight_skills
    LI_SYMBOL(fight_skills)
#endif

#ifndef LI_SYMBOL_name
#define LI_SYMBOL_name
    LI_SYMBOL(name)
#endif

