services:
  backend1:
    build: .
    ports:
      - "18081:18081"
    depends_on:
      - db
    environment:
      MONGO_URI: "mongodb://db:27017"
    networks:
      - crow-network

  backend2:
    build: .
    ports:
      - "18082:18082"
    depends_on:
      - db
    environment:
      MONGO_URI: "mongodb://db:27017"
    networks:
      - crow-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - crow-network

  load_balancer:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - crow-network

    
volumes:
  mongodb_data_container:

networks:
  crow-network:
