services:
  web1:
    build: .
    ports:
      - "18081:18080"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017

  web2:
    build: .
    ports:
      - "18082:18080"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
volumes:
  mongodb_data_container:
