services:
  backend1:
    build: .
    ports:
      - "18080"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017

  backend2:
    build: .
    ports:
      - "18081"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  load_balancer:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    
volumes:
  mongodb_data_container:
